apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: busybox
              args:
                - /bin/sh
                - -c
                - "echo Hello from CronJob at $(date)"
          restartPolicy: OnFailure
