replicaCount: 2

image:
  repository: artalll/quakewatch
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: quakewatch.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: FLASK_ENV
    value: production

configMap:
  enabled: true
  data:
    API_KEY: your-api-key

secret:
  enabled: true
  data:
    SECRET_KEY: your-secret-key

serviceAccount:
  create: false
  name: default
