alertmanager:
  enabled: true

server:
  service:
    type: ClusterIP

extraScrapeConfigs: |
  - job_name: 'quakewatch-app'
    static_configs:
      - targets: ['quakewatch.default.svc.cluster.local:5000']

# Alerting rules
serverFiles:
  alerting_rules.yml:
    groups:
      - name: quakewatch-alerts
        rules:
          - alert: PodCrashLooping
            expr: kube_pod_container_status_restarts_total > 3
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Pod {{ $labels.pod }} is restarting frequently"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} restarted more than 3 times."

          - alert: HighPodCPUUsage
            expr: sum(rate(container_cpu_usage_seconds_total{container!=""}[1m])) by (pod) > 0.3
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage for Pod {{ $labels.pod }}"
              description: "Pod {{ $labels.pod }} is using more than 30% CPU for over 1 minute."

          - alert: HighMemoryUsage
            expr: sum(container_memory_usage_bytes{container!=""}) by (pod) > 500000000
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage for Pod {{ $labels.pod }}"
              description: "Pod {{ $labels.pod }} is using more than 500MB of memory."

          - alert: PodNotReady
            expr: kube_pod_status_ready{condition="true"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Pod {{ $labels.pod }} is not ready"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has not been ready for more than 2 minutes."
